### ISSUE TITLE
Support for wildcard and fuzzy operators with qnames operator

### ISSUE THREAD

**Issue by rendel** [sirensolutions/siren#2]
Currently, it is not possible to mix the wildcard or fuzzy operator with the qnames operators. For example:
`
{
    "node": {
        "attribute": "@type",
        "query": "'namespace:Some*'"
    }
}
`

**Comment by fpompermaier** [comment]
+1

**Comment by stefanobortoli** [comment]
+1

**Comment by Blakko** [comment]
+1

**Comment by rendel** [comment]
Qnames withing a regexp query is now allowed. You should be able to query something like:
`
{ "node": { "attribute": "@type", "query": "/namespace:Some*/" } }
`

Wildcard queries such as 
`
{ "node": { "attribute": "@type", "query": "'namespace:Some*'" } }
`
are not allowed since they are nested into a protected query, which automatically escape all the special characters.
Allowing qnames outside the protected query was only possible for the regexp query, due to possible ambiguity problem in the query language grammar.

Fuzzy queries were already allowed with protected query:
`
{ "node": { "attribute": "@type", "query": "'namespace:Some'~" } }
`

**Comment by fpompermaier** [comment]
Great!
