### ISSUE TITLE
Conflicting license information 

### ISSUE THREAD

**Issue by fkleedorfer** [sirensolutions/siren#5]
AFAIK, siren is open source, with [Affero GPL and Apache 2 license depending on the modules](https://github.com/sindicetech/siren/blob/master/LICENSE.md). However, some files contain this copyright notice: 

```
<!--
 Copyright (c) 2014, Sindice Limited. All Rights Reserved.
 This file is part of the SIREn project.
 SIREn is not an open-source software. It is owned by Sindice Limited. SIREn
 is licensed for evaluation purposes only under the terms and conditions of
 the Sindice Limited Development License Agreement. Any form of modification
 or reverse-engineering of SIREn is forbidden. SIREn is distributed without
 any warranty.
-->
```

These files can be [found](https://github.com/sindicetech/siren/search?utf8=%E2%9C%93&q=+SIREn+is+not+an+open-source+software&type=Code) easily using the github in-repository search. 

It looks as if this latter notice is outdated, but clarification (or an update to these files) would be welcome.

**Comment by rendel** [comment]
Hi,

Thanks for reporting this issue. Indeed, this particular notice is outdated, and the current licensing is the one described in the [LICENSE](https://github.com/sindicetech/siren/blob/master/LICENSE.md) file. We will fix this issue in the next release.

**Comment by fkleedorfer** [comment]
Thanks for the clarification and the quick response!
